# Generated by Django 5.0.3 on 2024-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllink", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus_Uploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("syllabus", models.FileField(upload_to="syllabi/")),
            ],
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
