# Generated by Django 5.0.3 on 2024-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllink", "0002_syllabus_uploader_delete_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus_uploader",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
