# Generated by Django 5.0.3 on 2024-03-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("syllink", "0003_syllabus_uploader_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Syllabus_Uploader",
            new_name="SyllabusUploader",
        ),
    ]
